= Curriculum for https://isaqb.org[iSAQB] Enterprise Architecture Management for Software Architects

:toc:
:toc-placement!:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Status
image:https://github.com/isaqb-org/curriculum-eam/workflows/CI%20-%20Releases%20and%20Main/badge.svg?branch=main["CI – Releases and Main"]
image:https://img.shields.io/github/last-commit/isaqb-org/curriculum-eam/main.svg["Last commit"]
image:https://img.shields.io/github/contributors/isaqb-org/curriculum-eam.svg["Contributors",link="https://github.com/isaqb-org/curriculum-eam/graphs/contributors"]
image:https://img.shields.io/github/issues/isaqb-org/curriculum-eam.svg["Issues",link="https://github.com/isaqb-org/curriculum-eam/issues"]
image:https://img.shields.io/github/issues-closed/isaqb-org/curriculum-eam.svg["Issues closed",link="https://github.com/isaqb-org/curriculum-eam/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+"]


This is <<copyrighted,copyrighted work>>.

== Content
This repository contains the curriculum for the iSAQB Advanced Level module *Enterprise Architecture Management for Software Architects*

toc::[]

== How to contribute or participate
Create an issue or a pull-request

== How to use this template

. Clone the repository - including the submodule:
+
--
[source,shell]
----
Via SSH:
git clone git@github.com:isaqb-org/curriculum-eam.git --recursive

Via HTTPS:
git clone https://github.com/isaqb-org/curriculum-eam.git --recursive
----
--

. Build the project with http://www.gradle.com[gradle] (you need a locally installed JDK 17 or higher) via `./gradlew`.
. Once the "BUILD SUCCESSFUL" is show, you can review the build result under `./build/`

== Maintainers

This repository is currently maintained by the curators of the EAM module.
It was forked from https://github.com/isaqb-org/advanced-template,
so the contributors of that project basically contributed to this one, too.


[[copyrighted]]
== Licensing and Copyright

include::license-copyright/LICENSE.adoc[]
