=== {learning-goals}

// tag::DE[]

[[LZ-1-1]]
==== LZ 1-1: EAM-Definition und die Abgrenzung zu anderen Management-Bereichen
* Ziele und Nutzen des EAMs benennen und erklären können.
* EAM als Brücke zwischen der strategischen Unternehmensplanung und den Anwendungsprojekten verstehen.
* Zusammenspiel von EAM und anderen strategischen Managementaufgaben (z. B. Unternehmens- und Strategieplanung, IT-Strategie, IT-Management, Prozessmanagement, Projektmanagement, Innovationsmanagement, Change-Management etc.) verstehen.
* Abgrenzung zwischen Unternehmens-, IT- und Architektur-Governance erklären.
* Abgrenzung zwischen EAM und anderen Architekturbereichen erklären, z.B. IT-Architektur, Solution-Architektur und Software-Architektur.
* Rollen und Aufgaben des Architekturmanagements kennen und voneinander unterscheiden, z. B. Enterprise-Architekt, Domänen-Architekt, Solution-Architekt, Softwarearchitekt.

[[LZ-1-2]]
==== LZ 1-2: EAM-Grundbegriffe
* Die Begrifflichkeiten der ISO 42010 erklären können: Stakeholder, Concerns, Architecture Views, Architecture Models
* Architekturdomänen verstehen, inkl. wesentlicher Elemente der Domänen, z. B.:
** Geschäftsarchitektur
** Applikationsarchitektur (a.b.a. Informationssystem-Architektur)
** Daten-Architektur (a.b.a. Information-Architektur)
** Technologie-Architektur (a.b.a. Infrastruktur-Architektur)
* Abgrenzung und Zusammenhänge zwischen den Architekturdomänen verstehen.
* Zusammenhang zwischen den Architekturdomänen und der Softwarearchitektur verstehen.
* Architektur-Prinzipien sowie deren Nutzen und Konsequenzen kennen.
* Definition von Capabilities (a.b.a. Geschäftsdomänen) kennen.
* Unternehmensarchitektur-Roadmap erklären.
** Ist-, Ziel- und Soll-IT-Unternehmensarchitekturen kennen.
** Unterschied zwischen einem Unternehmens- und einem Softwaresystem-Implementierungsroadmap verstehen.

[[LZ-1-3]]
==== LZ 1-3: Überblick über die EAM-Frameworks und -Werkzeuge
* Unternehmensarchitektur-Frameworks und deren Nutzen kennen, z.B. TOGAF
* Architektur-Repositories sowie deren Einsatz, Nutzen und Herausforderungen bei der Unternehmensarchitektur kennen
* Verschiedene Architektur-Frameworks und deren Klassifizierung kennen, z. B.:
** Architektur-Frameworks, z. B. TOGAF, NAF, MoDAF, DoDAF, ITIL
** Taxonomien, z. B. Zachmann
** Branchenframeworks, z. B. BIAN, TM Forum Frameworx
** Prozess-Management Frameworks, z.B. PCF
* Berücksichtigung von Softwarearchitektur und Softwareentwicklung in Unternehmensarchitektur-Frameworks kennen.
// end::DE[]

// tag::EN[]
[[LZ-1-1]]
==== LZ 1-1: EAM definition and the relation to other management areas.
* Be able to name and explain the goals and benefits of EAM.
* Understand EAM as a bridge between strategic business planning and application projects.
* Understand the interaction of EAM and other strategic management tasks (e.g. corporate and strategic planning, IT strategy, IT management, process management, project management, innovation management, change management, etc.).
* Explain the distinction between corporate, IT, and architecture governance.
* Explain the distinction between EAM and other architecture areas, e.g. IT architecture, solution architecture and software architecture.
* Know and distinguish roles and tasks of architecture management, e.g. enterprise architect, domain architect, solution architect, software architect.

[[LZ-1-2]]
==== LZ 1-2: EAM basic terms.
* Be able to explain the terms used in ISO 42010: Stakeholders, Concerns, Architecture Views, Architecture Models.
* Understand architecture domains, including essential elements of the domains, e.g:
** Business architecture
** Application architecture (a.k.a. Information system architecture)
** Information system architecture (a.k.a. application architecture)
** Data architecture (a.k.a. information architecture)
** Technology architecture (a.k.a. infrastructure architecture)
* Understand the distinction and interrelationships between architectural domains.
* Understand the relationship between the architecture domains and software architecture.
* Know architecture principles and their benefits and consequences.
* Know the definition of capabilities (a.k.a. business domains).
* Know what an enterprise architecture roadmap is.
** Know baseline, target, and transition IT enterprise architectures.
** Differentiate between an enterprise and software system implementation roadmap.

[[LZ-1-3]]
==== LZ 1-3: Overview of EAM frameworks and tools.
* Know different enterprise architecture frameworks and their benefits, e.g. TOGAF.
* Know architecture repositories and their use, benefits, and challenges in enterprise architecture.
* Know different architecture frameworks and their classification, e.g.:
** Architecture frameworks, e.g. TOGAF, NAF, MoDAF, DoDAF, ITIL.
** Taxonomies, e.g. Zachmann
** Industry frameworks, e.g. BIAN, TM Forum Frameworx
** Process management frameworks, e.g. PCF
* Know how software architecture and software development are represented in enterprise architecture frameworks.

// end::EN[]


