=== {learning-goals}

// tag::DE[]
[[LZ-1-1]]
==== LZ 1-1: Was sollen die Teilnehmer können?
* Aufgaben, Ziele und Nutzen des EAM benennen und erklären können. 
* Zusammenspiel von EAM und anderen strategischen Managementaufgaben (z.B. Unternehmensplanung, Portfoliomanagement, Produktionsmanagement, etc.) darstellen und erklären. 
* Abgrenzung von EAM und E(IT)AM erklären. 
* Zusammenspiel von (IT-)Strategie und EAM. 
* Strategische Anwendungsplanung: Ist-, Ziel- und Soll-IT-Unternehmensarchitektur. 
* Bewertung eines Anwendungsportfolios erklären und durchführen. 
* Definition und Nutzen von Capabilities darstellen und erklären. 
* Aufgaben und Herausforderungen der Governance benennen und erklären. 
* Governance-Ebenen (Corporate-, IT-, Architecture-, SOA-) abgrenzen und erklären. 
* Anforderungen an EAM Werkzeuge benennen und erklären

[[LZ-1-2]]
==== LZ 1-2: Was sollen die Teilnehmer verstehen?
* Funktion des EAM im Planungssystem eines Unternehmens
* Bedeutung, Herausforderungen und Nutzen der strategischen IT-Planung
* Funktion der IT-Strategie in der Unternehmensstrategie 
* Funktion des Anwendungsportfolio-Managements
* Abgrenzung zwischen Ist-, Ziel- und Soll-IT-Unternehmensarchitektur.
* Berührungspunkte zwischen EAM und wirtschaftlichem Management
* Gestaltung und Zusammenspiel von Ist-, Ziel- und Soll-IT-Unternehmensarchitektur
* Funktion und Abgrenzung der Geschäfts-, Anwendungs-, Daten- und Technologie-Architektur 
* Funktion des IT-Risk-Management, Compliance und IT-Security
* Zusammenhang von Change-Management und EAM
* Einsatz eines Repositories zur Verwaltung und Standardisierung der Unternehmens-IT 
* Abgrenzung verschiedener Unternehmensarchitektur-Frameworks (z.B. TOGAF, COBIT, ITIL, TM Forum Frameworx, etc.)

[[LZ-1-3]]
==== LZ 1-3: Was sollen die Teilnehmer kennen?
* Aufwand und Nutzen des EAM
* Bedeutung der Prozesslandkarte für die Unternehmensarchitektur
* Typische EAM-Visualisierungen, wie z.B. Bebauungsplan-Grafik, Portfolio-Grafik, Informationsfluss-Grafik, Cluster-Grafik oder Masterplan-Grafik
* Kennzahlen des EAM und anderen Quellen für die strategische Planung der IT-Landschaft, wie z.B. IT-Performance, Kosten, Wettbewerbsdifferenzierung, etc.
// end::DE[]

// tag::EN[]
[[LG-1-1]]
==== LG 1-1: The is the first learning goal, in category xy
tbd.
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
