=== {learning-goals}


// tag::DE[]
[[LZ-5-1]]
==== LZ 5-1: Was sollen die Teilnehmer können?
* Grundlegende Einführungspfade für ein EAM darstellen und erklären.
* Organisation der Einführung und Optimierung eines EAM darstellen und erklären.
* Herausforderungen und Erfolgsfaktoren bei der Einführung eines EAM darstellen und erklären.
* Stakeholder-Analyse für eine EAM-Einführung darstellen und erklären.
* Zweck und Nutzen einer EAM-Einführung an Stakeholder kommunizieren.
* Migrationspfade für die Einführung eines EAM in eine bestehende IT-Landschaft darstellen und erklären.
* Iteratives Vorgehen bei der Einführung eines EAM in eine bestehende IT-Landschaft darstellen und erklären.
* Grenzen bei der Einführung eines EAM in eine bestehende IT-Landschaft darstellen und erklären.

[[LZ-5-2]]
==== LZ 5-2: Was sollen die Teilnehmer verstehen?
* Phasen bei der Einführung eines EAM
* Auswahl der Migrationsschritte bei der Einführung eines EAM in eine bestehende IT-Landschaft

[[LZ-5-3]]
==== LZ 5-3: Was sollen die Teilnehmer kennen?
* Beispielszenarien für die Einführung eines EAM
* Beispielszenarien für die Einführung eines EAM in eine bestehende IT-Landschaft
* Soll-Landschaft
// end::DE[]

// tag::EN[]
[[LG-5-1]]
==== LG 5-1: What should the participants be able to do?
* Describe and explain fundamental implementation paths for an EAM system.
* Describe and explain the organisation of introduction and optimisation of an EAM system.
* Describe and explain the challenges and success factors associated with introduction of an EAM system.
* Describe and explain stakeholder analysis for introduction of EAM.
* Communicate the purpose and benefits of introducing EAM.
* Describe and explain migration paths for the introduction of EAM into an existing IT landscape.
* Describe and explain the iterative procedure for the introduction of EAM into an existing IT landscape. Describe and explain limitations on the introduction of EAM into an existing IT landscape.

[[LG-5-2]]
==== LG 5-2: What should the participants understand?
* The phases involved in introduction of EAM
* Selection of the migration steps for the introduction of EAM into an existing IT landscape.

[[LG-5-3]]
==== LG 5-3: What should the participants know?
* Example scenarios for the introduction of EAM
* Example scenarios for the introduction of EAM into an existing IT landscape
* The target landscape.
// end::EN[]


