=== {learning-goals}


// tag::DE[]
[[LZ-6-1]]
==== LZ 6-1: Was sollen die Teilnehmer können?
* Anforderungen und Nutzen von Unternehmensarchitektur-Framework benennen und erklären.
* Arten von Architektur-Frameworks unterscheiden und erklären können: 
** Operationelle Frameworks (z.B. TOGAF)
** Konzeptionelle Frameworks (z.B. Zachmann)
** Branchenframeworks (z.B. TM Forum Frameworx) 
* Einsatzgebiete, Verwendungszwecke und Zielgruppen der verschiedenen Arten von Architektur-Frameworks benennen und erklären. 
* Abgrenzung der verschiedenen Arten von Architektur-Frameworks benennen und erklären
* Bedeutung von Referenzmodellen und –architekturen in den verschiedenen Architektur-Frameworks benennen und erklären.

[[LZ-6-2]]
==== LZ 6-2: Was sollen die Teilnehmer verstehen?
* Wesentliche Inhalte des TOGAF
* Wesentliche Inhalte des COBIT-Frameworks
* Wesentliche Inhalte des Zachman-Frameworks
* Berücksichtigung von „klassischen“ IT-Disziplinen wie Software-Architektur, Geschäftsprozessmodellierung und Software-Entwicklung in Unternehmensarchitektur-Frameworks
* Herausforderungen beim Einsatz eines Unternehmensarchitektur-Frameworks
* Auswahl und Tailoring eines Unternehmensarchitektur-Frameworks für ein Unternehmen

[[LZ-6-3]]
==== LZ 6-3: Was sollen die Teilnehmer kennen?
* TOGAF Architecture Development Methode (ADM)
* TOGAF Architecture Content Framework
* TOGAF Architecture Capability Framework
* TOGAF Architecture Governance
* Beispiele für den Anpassungsaufwand bei der Verwendung eines Frameworks für ein konkretes Unternehmen
* Zachman Framework
* ARIS-Methode
* Common Information Model (CIM)
* TM Forum Frameworx
* Department of Defence Architecture Framework (DoDAF)
* Ministry of Defence Architectual Framework (MoDAF)
// end::DE[]

// tag::EN[]
[[LG-6-1]]
==== LG 6-1: What should the participants be able to do?
* List and explain requirements on and benefits of enterprise architecture frameworks. 
* Differentiate between and explain the types of architecture frameworks: 
** Operational frameworks (e.g., TOGAF)
** Conceptional frameworks (e.g., Zachmann)
** Business sector frameworks (e.g., TM Forum Frameworx). 
* List and explain application areas, purposes and target groups of the different types of architecture frameworks. 
* Explain the differences between the different types of architecture frameworks. 
* Explain the significance of reference models and architectures in the different architecture frameworks.

[[LG-6-2]]
==== LG 6-2: What should the participants understand?
* The essential elements of TOGAF
* The essential elements of the COBIT framework
* The essential elements of the Zachman framework
* The consideration of “classic” IT disciplines such as software architecture, business process modelling and software development in enterprise architecture frameworks
* Challenges in the use of an enterprise architecture framework
* Selection and tailoring of an enterprise architecture framework for a company.

[[LG-6-3]]
==== LG 6-3: What should the participants know?
* The TOGAF Architecture Development Method (ADM)
* The TOGAF architecture content framework
* The TOGAF architecture capability framework
* TOGAF architecture governance
* Examples for the customisation effort when using a framework for a specific company
* The Zachman framework
* The ARIS approach
* The Common Information Model (CIM)
* The TM Forum Frameworx
* The Department of Defense Architecture Framework (DoDAF)
* The Ministry of Defence Architectural Framework (MoDAF)
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
