// tag::DE[]
|===
| Dauer: 270 Min. | Übungszeit: 120 Min.
|===

=== Begriffe und Konzepte
Mission, Vision, Architekturvision, Unternehmensprinzipien, Architekturprinzipien, Geschäftsmodell, Geschäftsarchitektur, Ordnungsrahmen für IT-Strategie,Anwendungsportfolio-Management, Informationssystem-Architektur, Daten-Architektur, Technische Architektur, Geschäftsprozessmodellierung, Business Motivation Model (BMM), TOGAF Architecture Development Method (ADM), SWOT-Analyse, Maturitätsanalyse, Nutzwertanalyse, GAP-Analyse, Impact-Analyse, Risiko-Analyse, Capability Analyse, Capability-basierte Planung, Szenario-basierte Bewertung.

// end::DE[]

// tag::EN[]
|===
| Duration: 270 min | Practice time: 120 min
|===

=== Terms and Principles
Mission, vision, architecture vision, corporate principles, architecture principles, business model, business architecture, regulatory framework for the IT strategy, application portfolio management, information system architecture, data architecture, technical architecture, business process modelling, Business Motivation Model (BMM), TOGAF Architecture Development Method (ADM), SWOT analysis, maturity analysis, benefit analysis, GAPanalysis, impact analysis, risk analysis, capability analysis, capability-based planning, scenario-based evaluation.

// end::EN[]




