=== {learning-goals}

// tag::DE[]

[[LZ-2-1]]
==== LZ 2-1: allgemeine Vorgehensweise zur (Weiter-)Entwicklung einer Unternehmensarchitektur
* Die Beteiligung des Softwarearchitekten bei der Ableitung der IT-Unternehmensarchitektur aus der Unternehmensstrategie kennen.
* Verschiedene Instrumente und Verfahren zur Bewertung von vorhandenen Architekturen kennen, z. B. Reifegradanalyse, Gap-Analyse, Impact-Analyse, Risiko-Analyse, Szenario-basierte Bewertung.
* Typische EAM-Visualisierungen, wie z. B. Bebauungsplan-Grafik, Portfolio-Grafik, Informationsfluss-Grafik, Cluster-Grafik oder Roadmap-Grafik kennen.
* Verstehen, dass unterschiedliche Architekturentscheidungen getroffen werden könnten, wenn sie aus Sicht des Unternehmensarchitekten oder aus Sicht des Softwarearchitekten betrachtet werden.
* Verschiedene Vorgehensweisen zur (Weiter-)Entwicklung von Unternehmensarchitekturen kennen, z. B.:
** Top-Down, Bottom-Up
** Prozessorientiertes Vorgehen, z. B. TOGAF ADM
** Capability-Based Planning
** Application-Portfolio-Management
** Musterorientiertes Vorgehen, z.B. SEBIS Technische Universität München
** Risikogesteuerte Weiterentwicklung
* Die Auswirkung der Unternehmenskultur auf die Vorgehensweise kennen.
* Die Berücksichtigung von Softwarearchitektur in den verschiedenen Vorgehensweisen kennen.

[[LZ-2-2]]
==== LZ 2-2: Business-Capabilities als Brücke zwischen Geschäfts- und Softwarearchitektur
* Definition, Nutzen und Anwendungsbereiche von Business-Capabilities erklären.
* Zusammenhang zwischen Business-Capabilities und Architekturdomänen kennen.
* Bezug von Business-Capabilities zu Softwarearchitekturmethoden, z.B. Domain-Driven-Design kennen.

[[LZ-2-3]]
==== LZ-2-3: Methoden zur Aufnahme und Analyse der Ist-Architektur
* Herausforderungen bei der Beschreibung und Modellierung der Ist-Architektur kennen.
* Ansätze zur Analyse der Ist-Architektur verstehen, z. B. Risikoanalyse, Reifegradanalyse, Kosten-Nutzen-Analyse usw.

[[LZ-2-4]]
==== LZ 2-4: Methoden zur (Weiter-)Entwicklung der Ziel-Architektur
* Analyse der Geschäftstreiber, -strategie und -anforderungen als Basis für die Ziel-Architektur verstehen.
* Entwicklung der applikationsübergreifende Zielarchitektur darstellen und erklären.
* Notwendigkeit zur kontinuierlichen Fortschreibung der Ziel-Architektur verstehen.

[[LZ-2-5]]
==== LZ 2-5: Methoden zur (Weiter-)Entwicklung der Architektur-Roadmap
* Ableitung der Soll-Architektur aus Ist- und Zielarchitektur verstehen.
* Impact- und Gap-Analyse kennen.
* Vorgehensweise zur Architekturplanung (Roadmap) erklären können.
* Notwendigkeit zur kontinuierlichen Fortschreibung der Roadmap verstehen.

[[LZ-2-6]]
==== LZ 2-6: Architekturprinzipien
* Architekturprinzipien als Bestandteil der Unternehmensarchitektur verstehen.
* Kategorisierung von Architekturprinzipien kennen.
* TOGAF-Architekturprinzipienkatalog kennen.

[[LZ-2-7]]
==== LZ 2-7: Referenzmodelle bzw. -architekturen
* Standards, Referenzmodelle, Best Practices, Architekturrichtlinien und -Prinzipien als Treiber für Qualität verstehen.
* Definition und Einsatz von Referenzarchitekturen kennen.
* Beispiele für Referenzarchitekturmodelle kennen, z.B.:
** TOGAF-Referenzmodelle
** Branchenspezifische Referenzmodelle, z. B. TM-Forum, BIAN, Frameworx, etc.
** Systemübergreifende Architekturmuster, z. B. Microservices, Event- bzw. Message-Driven, Composable Architecture usw.
** Integrationsmuster
* Referenzmodelle als Mittel zum Wissensmanagement / -transfer kennen.
* Die Herausforderungen (z.B. Abstraktionsgrad, Rahmenbedingungen) bei der Weiterentwicklung der Referenzmodelle kennen.
* Abgrenzung und Zusammenhänge zwischen Referenzmodellen auf der Unternehmens- und der Softwarearchitektur-Ebene kennen.

[[LZ-2-8]]
==== LZ 2-8: EAM-Repository
* Funktion und Nutzen von EAM-Repositories verstehen, z.B. Historisierung, Deltaermittlung und Versionierung.
* Herausforderungen bei der Pflege und die Aktualisierung der Daten in das Repository kennen.
* Herausforderungen bei der Beschreibung der unterschiedlichen Architekturdomänen (z.B. Geschäfts-, Informations-, Applikations- und Technologe-Domäne) sowie Architekturebenen (z. B. Übergänge zwischen Unternehmensarchitektur, Solution-Architektur und Softwarearchitektur) verstehen.
* Informationsarten in einem EAM-Repository benennen können, z.B.:
** Architektur-Metamodell, z.B. vom TOGAF Architecture Content Framework
** Dokumentation von Ist-, Soll- und Zielarchitekturen
** Standards (Industriestandards, etc.)
** Referenzbibliothek (Referenzarchitekturen, Vorlagen, Muster, etc.), z.B. TOGAF-Referenzmodelle

// end::DE[]

// tag::EN[]
[[LG-2-1]]
==== LG 2-1: General approaches for developing and enhancing an enterprise architecture.
* Know how the software architects are involved in deriving the IT enterprise architecture from the enterprise strategy.
* Know different tools and approaches to assess existing architectures, e.g. maturity analysis, gap analysis, impact analysis, risk analysis, scenario-based assessment.
* Know typical EAM visualisations, such as blueprints, portfolio graphic, information flow graphic, cluster graphic, or roadmap graphic.
* Understand that different architectural decisions could be made when viewed from the enterprise architect's perspective or from the software architect's perspective.
* Know the different approaches to develop or enhance enterprise architectures, e.g.:
** Top-down, bottom-up
** Process-oriented approach, e.g. TOGAF ADM
** Capability-based planning
** Application portfolio management
** Pattern-oriented approach, e.g. SEBIS Technical University of Munich
** Risk-driven further development
* Know the impact of the corporate culture on the approach.
* Know how software architecture is addressed in the different approaches.

[[LG-2-2]]
==== LG 2-2: Business capabilities as a link between business and software architecture.
* Explain the definition, benefits, and uses of business capabilities.
* Know the relationship between business capabilities and architecture domains.
* Know the relation of business capabilities to software architecture methodologies, e.g., domain-driven design.

[[LG-2-3]]
==== LG-2-3: Methods for specifying and analyzing the baseline architecture.
* Know the challenges in describing and modeling the baseline architecture.
* Understand the approaches to analyzing the baseline architecture, e.g., risk analysis, maturity analysis, cost-benefit analysis, etc.

[[LG-2-4]]
==== LG 2-4: Methods for developing and changing the target architecture.
* Understand that the analysis of the business drivers, strategy, and requirements are a basis for the target architecture.
* Present and explain the evolution of a target architecture that impacts multiple applications.
* Understand the need to continuously update the target architecture.

[[LG-2-5]]
==== LG 2-5: Methods for developing and changing the architecture roadmap.
* Understand how to derive transition architectures from the baseline and target architectures.
* Know impact and gap analysis.
* Be able to explain the approach for architecture planning (roadmap).
* Understand the need to continuously update roadmap.

[[LG-2-6]]
==== LG 2-6: Architecture Principles
* Understand architecture principles as a part of enterprise architecture.
* Know how to categorize architecture principles.
* Know the TOGAF architecture principles catalog.

[[LG-2-7]]
==== LG 2-7: Reference models or architectures.
* Understand standards, reference models, best practices, architecture guidelines, and principles as drivers of quality.
* Know the definition and use of reference architectures.
* Know examples of reference architecture models, e.g.:
** TOGAF reference models
** Industry-specific reference models, e.g., TM Forum, BIAN, Frameworx, etc.
** Architecture patterns that impact multiple systems, e.g. microservices, event- or message-driven, composable architecture, etc.
** Integration patterns
* Know reference models as a means of knowledge management / transfer.
* Know the challenges (e.g., level of abstraction, constraints) in evolving reference models.
* Know the differences and relationships between reference models at the enterprise and software architecture levels.

[[LG-2-8]]
==== LG 2-8: EAM Repository
* Understand the function and benefits of EAM repositories, e.g., maintaining a history of changes, determining the delta, and versioning.
* Know the challenges in maintaining and updating data in the repository.
* Understand the challenges in describing different architectural domains (e.g., business, information, application, and technology domains) and architectural layers (e.g., transitions between enterprise architecture, solution architecture, and software architecture).
* Be able to name the types of information in an EAM repository, e.g.:
** Architecture metamodel, e.g. from the TOGAF Architecture Content Framework
** Documentation of baseline, transition, and target architectures
** Standards (industry standards, etc.)
** Reference library (reference architectures, templates, patterns, etc.), e.g., TOGAF reference models

// end::EN[]


