// tag::DE[]
=== Voraussetzungen

Teilnehmerinnen und Teilnehmer **sollten** folgende Kenntnisse und/oder Erfahrung mitbringen:
* Grundlagen der Architekturentwicklung: Bedeutung und Abgrenzung von Architektur, Vorgehen, Einfl체sse und Anforderungen, Architekturentscheidungen, Muster und Dokumentation mit Sichten, wie im CPSA-F Foundation Level vermittelt.

**Hilfreich** f체r das Verst채ndnis einiger Konzepte sind dar체ber hinaus:
* Praktische Erfahrung im Architekturbereich und Einblick in mindestens eine moderne Technologie oder Plattform zur Entwicklung von verteilten Anwendungen
* Kenntnis typischer Herausforderungen im Bereich von Unternehmensarchitekturen:
** Definition von (IT-)Unternehmenszielen
** Strategische (IT-)Planung
** (IT-)Portfolio-Management
** Applicaiton Lifecycle Management
** IT-Infrastructure-Library (ITIL)
// end::DE[]

// tag::EN[]
=== Prerequisites

Participants **should** have the following prerequisite knowledge:
- Fundamentals of architecture development: Importance and delimitation ofarchitecture, procedures, influences and requirements, architecture decisions, models and documentation with views, as taught at the CPSA-F Foundation Level.

Knowledge in the following areas may be **helpful** for understanding some concepts:
* Practical experience in the architecture field and an insight into at least one modern technology or platform for development of distributed applications.
* Knowledge of typical challenges in the field of enterprise architectures:
** Definition of (IT) enterprise objectives
** Strategic (IT) planning
** (IT) portfolio management.
** Applicaiton Lifecycle Management
** IT-Infrastructure-Library (ITIL)
// end::EN[]

