// tag::DE[]
=== Voraussetzungen

Teilnehmerinnen und Teilnehmer **sollten** folgende Kenntnisse und/oder Erfahrung mitbringen:

- Grundlagen der Architekturentwicklung: Bedeutung und Abgrenzung von Architektur, Vorgehen, Einflüsse und Anforderungen, Architekturentscheidungen, Muster und Dokumentation mit Sichten, wie im CPSA-F Foundation Level vermittelt.
- Grundlagen der Betriebswirtschaftslehre: Entwicklung von Strategien und Geschäftsmodellen, Geschäftsprozessmanagement, Organisation. 
- Wünschenswert für das Verständnis einiger Konzepte ist praktische Erfahrung im Architekturbereich und Einblick in mindestens eine moderne Technologie oder Plattform zur Entwicklung von verteilten Anwendungen

**Hilfreich** für das Verständnis einiger Konzepte sind darüber hinaus:

- Kenntnis typischer Herausforderungen im Bereich von Unternehmensarchitekturen:
  * Definition von (IT-)Unternehmenszielen
  * Strategische (IT-)Planung
  * (IT-)Portfolio-Management
- Weiterführende Kenntnisse in Betriebswirtschaftslehre:
  * Controlling
  * Kosten-Nutzen-Rechnung
  * Investitionsrechnung
// end::DE[]

// tag::EN[]
=== Prerequisites

Participants **should** have the following prerequisite knowledge:

- Prerequisite 1
- Prerequisite 2, etc.

Knowledge in the following areas may be **helpful** for understanding some concepts:

- Area 1:
  * Knowledge 1
  * Experience 2
  * Knowledge 3
  * Experience 4
  * Understanding 5
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Kenntnisgruppen sowie Voraussetzungen bitte entsprechend ausformulieren!
====
// end::REMARK[]
