=== {learning-goals}

// tag::DE[]

[[LZ-3-1]]
==== LZ 3-1: EAM-Repository
* Funktion und Nutzen von EAM-Repositories verstehen, z.B. Historisierung, Deltaermittlung und Versionierung.
* Herausforderungen bei der Pflege und die Aktualisierung der Daten in der Repository kennen.
* Verschiedene Werkzeuge für die Erarbeitung und Verwaltung einer Unternehmensarchitektur kennen.
* Herausforderungen bei der Beschreibung der unterschiedlichen Architekturdomänen (z.B. Geschäfts-, Informations-, Applikations- und Technologe-Domäne) sowie Architekturebenen (z. B. Übergänge zwischen Unternehmensarchitektur, Solution-Architektur und Softwarearchitektur) verstehen.

[[LZ-3-2]]
==== LZ 3-2: Metamodelle
* Funktion und Nutzen von Metamodellen kennen.
* Verknüpfung zwischen Softwarearchitekturen und EA-Metamodellen (z. B. TOGAF) kennen.
* Informationsarten in einem EAM-Repository benennen können, z.B.:
** Architektur-Metamodell, z.B. vom TOGAF Architecture Content Framework
** Dokumentation von Ist-, Soll- und Zielarchitekturen
** Standards (Industriestandards, etc.)
** Referenzbibliothek (Referenzarchitekturen, Vorlagen, Muster, etc.), z.B. TOGAF-Referenzmodelle

// end::DE[]

// tag::EN[]

[[LZ-3-1]]
==== LZ 3-1: EAM Repository
* Understand the function and benefits of EAM repositories, e.g., maintaining a history of changes, determining the delta (differences), and versioning.
* Know the challenges in maintaining and updating data in the repository.
* Know the different tools for elaborating and managing an enterprise architecture.
* Understand the challenges in describing different architectural domains (e.g., business, information, application, and technology domains) and architectural layers (e.g., transitions between enterprise architecture, solution architecture, and software architecture).

[[LZ-3-2]]
==== LZ 3-2: Metamodels
* Know the function and utility of metamodels.
* Know the relation between software architectures and EA metamodels (e.g., TOGAF).
* Be able to name the types of information in an EAM repository, e.g.:
** Architecture metamodel, e.g. from the TOGAF Architecture Content Framework
** Documentation of baseline, transition, and target architectures
** Standards (industry standards, etc.)
** Reference library (reference architectures, templates, patterns, etc.), e.g., TOGAF reference models

// end::EN[]


